name: PIB Scraper and Processor

on:
  schedule:
    - cron: '30 16 * * *'  # 10 PM IST (16:30 UTC)
  workflow_dispatch:

env:
  AWS_REGION: 'ap-south-1'
  RAW_BUCKET: 'rawmodiscraped'
  PROCESSED_BUCKET: 'processedmodiscraped'
  PYTHON_VERSION: '3.10'
  PIP_CACHE_DIR: ~/.cache/pip
  TZ: 'Asia/Kolkata'  # Force IST timezone

jobs:
  scrape-and-process:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python${{ env.PYTHON_VERSION }}/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m nltk.downloader punkt

      - name: Run scraper
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "Running scraper for date: $CURRENT_DATE (IST)"
          python pmScraper.py --date "$CURRENT_DATE"

      - name: Upload raw data to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          CURRENT_DATE=$(date +'%Y/%m/%d')
          python -c "
          import boto3
          s3 = boto3.client('s3',
                aws_access_key_id='${{ secrets.AWS_ACCESS_KEY_ID }}',
                aws_secret_access_key='${{ secrets.AWS_SECRET_ACCESS_KEY }}',
                region_name='${{ env.AWS_REGION }}')
          s3.upload_file(
              'press_releases.jsonl',
              '${{ env.RAW_BUCKET }}',
              '$CURRENT_DATE/press_releases.jsonl'
          )"

      - name: Process with OpenRouter
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          CURRENT_DATE=$(date +'%Y/%m/%d')
          python process_with_ai.py \
            --input s3://${{ env.RAW_BUCKET }}/$CURRENT_DATE/press_releases.jsonl \
            --output s3://${{ env.PROCESSED_BUCKET }}/$CURRENT_DATE/processed.json \
            --api-key ${{ secrets.OPENROUTER_API_KEY }}
